services:
  db:
    image: mariadb:latest
    restart: on-failure
    volumes:
      - ./data/wordpress.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      MARIADB_ROOT_PASSWORD: wordpress
      MARIADB_DATABASE: wordpress

  wp:
    depends_on:
    - db
    build:
      context: .
      args:
        TAG: php8.2-apache
    volumes:
    - ./data/wp:/var/www/html
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        @error_reporting(E_ALL);
        @ini_set('log_errors', true);
        define('WP_DEBUG_DISPLAY', false);
        define('WP_DEBUG_LOG', true);
        define( 'SMTP_SERVER', 'sendria' );
        define( 'SMTP_PORT', 1025 );

# Database web interface.
  adminer:
    image: ghcr.io/shyim/adminerevo:latest
    restart: on-failure

# Formerly MailTrap. SMTP/Email catcher.
  sendria:
    #image: msztolcman/sendria:v2.2.2.0
    build: https://github.com/msztolcman/sendria.git
    restart: unless-stopped

  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy/config:/config
      - ./data/caddy/data:/data
    environment:
      # See https://github.com/CaddyBuilds/caddy-cloudflare?tab=readme-ov-file#configuration
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      DOMAIN: ${DOMAIN}
